spring:
  datasource:
    url: jdbc:sqlserver://wrapper:1533;databaseName=ats;encrypt=false;trustServerCertificate=true;
    username: sa
    password: Dat@bas3
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID_DEV}
            client-secret: ${CLIENT_SECRET_DEV}

server:
  port: 6000
