name: Maven Build & Package

on:
  push:
    branches: [main]
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven
      - name: install custom local model
        run: |
          git clone https://github.com/themajorones/models.git
          cd models && mvn clean install
      - name: Build with Maven
        run: ./mvnw clean package -B

      - name: Verify WAR
        run: |
          ls -l target/*.war

      - name: Upload WAR artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: autotest-build-artifacts
          path: target/*.war
          retention-days: 30
